ldap_user.settings:
  type: config_object
  mapping:
    drupalAcctProvisionServer:
      label: 'LDAP server providing provisioning data'
      type: string
    ldapEntryProvisionServer:
      label: 'LDAP server to provision LDAP entries on'
      type: string
    drupalAcctProvisionTriggers:
      label: 'drupalAcctProvisionTriggers'
      type: sequence
      sequence:
        type: string
    ldapEntryProvisionTriggers:
      label: 'ldapEntryProvisionTriggers'
      type: sequence
      sequence:
        type: string
    orphanedDrupalAcctBehavior:
      label: 'orphanedDrupalAcctBehavior'
      type: string
    orphanedCheckQty:
      label: 'orphanedCheckQty'
      type: integer
    orphanedAccountCheckInterval:
      label: 'Orphaned account checking interval'
      type: string
    userConflictResolve:
      label: 'userConflictResolve'
      type: integer
    manualAccountConflict:
      label: 'manualAccountConflict'
      type: integer
    acctCreation:
      label: 'Application of Drupal account settings to LDAP authenticated users'
      type: integer
    ldapUserSyncMappings:
      label: 'ldapUserSyncMappings'
      type: mapping
